1 - Importar dados

In [1]:
import pandas as pd
import plotly.express as px
import openpyxl as xl

data = pd.read_excel("new_clients.xlsx")

display(data)

     customer_id  join_date  city_id  gender_id
0              1 2022-01-08        7          1
1              2 2023-05-02       20          2
2              3 2023-05-14       15          1
3              4 2022-11-25       11          2
4              5 2023-04-26        8          1
..           ...        ...      ...        ...
995          996 2022-10-28        3          1
996          997 2022-07-07       20          2
997          998 2024-03-09       11          2
998          999 2022-07-16        6          1
999         1000 2024-04-08        2          2

[1000 rows x 4 columns]

2 - Limpar os Dados

In [2]:
data = data.rename(columns={"join_date": "Entrada", "gender_id": "Genero"}).drop(["customer_id", "city_id"], axis = 1)

display(data)

       Entrada  Genero
0   2022-01-08       1
1   2023-05-02       2
2   2023-05-14       1
3   2022-11-25       2
4   2023-04-26       1
..         ...     ...
995 2022-10-28       1
996 2022-07-07       2
997 2024-03-09       2
998 2022-07-16       1
999 2024-04-08       2

[1000 rows x 2 columns]

In [3]:
data["Genero"] = data["Genero"].replace({1:"Feminino",2:"Masculino"})

display(data)

       Entrada     Genero
0   2022-01-08   Feminino
1   2023-05-02  Masculino
2   2023-05-14   Feminino
3   2022-11-25  Masculino
4   2023-04-26   Feminino
..         ...        ...
995 2022-10-28   Feminino
996 2022-07-07  Masculino
997 2024-03-09  Masculino
998 2022-07-16   Feminino
999 2024-04-08  Masculino

[1000 rows x 2 columns]

3 - Checar Informações dos Dados

In [4]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Entrada  1000 non-null   datetime64[us]
 1   Genero   1000 non-null   object
dtypes: datetime64[us](1), object(1)
memory usage: 15.8+ KB

4 - Estruturar o Gráfico

In [5]:
#Quant. de Entradas
entry = data.groupby('Entrada').size().reset_index(name='Data')


display(data)

       Entrada     Genero
0   2022-01-08   Feminino
1   2023-05-02  Masculino
2   2023-05-14   Feminino
3   2022-11-25  Masculino
4   2023-04-26   Feminino
..         ...        ...
995 2022-10-28   Feminino
996 2022-07-07  Masculino
997 2024-03-09  Masculino
998 2022-07-16   Feminino
999 2024-04-08  Masculino

[1000 rows x 2 columns]

In [6]:
#Média gráfica + Criação do Gráfico
custom = entry.copy()
custom['Suave'] = custom['Data'].rolling(window=100).mean()
custom = custom.dropna()


fig = px.line(
    custom,
    x='Entrada',
    y='Suave',
    title= 'Média Entrada de Clientes',
    labels={'Entrada':'Data','Suave':'Média de entradas'},
    render_mode='svg'
)

fig.update_traces(
    line=dict(width=3, color='#FF0000'),
    mode='lines'
)

fig.update_layout(
    template='plotly_white',
    hovermode='x unified'
)

fig.show()